### ISSUE TITLE
Logické a technické chyby ve verzi 2020.11

### ISSUE THREAD

**Issue by jaandrle** [jaandrle/jaandrle.github.io#97]
### přístupnost
- [x] navrátit `role=*`, viz https://twitter.com/jaandrle/status/1364168178335637510
- [x] [Srovnejte si to v <head> | PageSpeed.cz - Na rychlosti záleží](https://pagespeed.cz/blog/srovnejte-si-to-v-head)
### drobnosti
- [ ] zobrazovat `updated` také v seznamech článků?
- [ ] `tabindex` pro `code` viz https://www.smashingmagazine.com/2022/11/guide-keyboard-accessibility-html-css-part1/
### roboti
- [ ] [Robots.txt neslouží k zákazu indexace stránek | Digichef](https://digichef.cz/zakaz-indexace) (viz odkaz na můj níže)

### web.dev/measure
- [ ] https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fjaandrle.github.io%2F#performance
- [ ] https://defaced.dev/tools/layout-shift-gif-generator/
- [ ] https://observatory.mozilla.org/analyze/jaandrle.github.io

### (Zapomenutý) variabilní font?
- [ ] `display: fallback` (má školení vzhůru dolů)
- [ ] [Font style matcher](https://meowni.ca/font-style-matcher/) (viz níže)
- [ ] u mně asi jen kvůli requestům?
- [ ] [Variable fonts guide - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)
- [ ] [iA-Fonts/iA Writer Duo/Variable at master · iaolo/iA-Fonts](https://github.com/iaolo/iA-Fonts/tree/master/iA%20Writer%20Duo/Variable)
- [ ] [Wakamai Fondue, the tool that answers the question “what can my font do?”](https://wakamaifondue.com/)

---
---

```
rel="nofolow noreferrer noopener"
```
---
https://github.com/jaandrle/jaandrle.github.io/blob/b720a396f90570244dfab642c2c00d474c512287/technical_txts/robots.txt#L7
---
```CSS
prvek {
    font-family: "Lucida Console", Monaco, monospace;
    font-size: 16px;
    line-height: 1.3;
    letter-spacing: 1.25px;
    word-spacing: 1.5px;
    font-weight: 300;
}
prvek {
    font-size: 15px;
    line-height: 1.4;
    font-family: "iAWriterDuospace-Regular.woff2";
}
```
